#!/bin/bash
### The script starts the server with default settings 

if python3 -c "import django" &> /dev/null; then
	python3 manage.py runserver
elif python -c "import django" &> /dev/null; then
	python manage.py runserver
else
	echo "Ooops, looks like either python or django is not installed."
fi

# -- END --
