# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171210_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='birth_date',
        ),
    ]
