# Generated by Django 2.0 on 2017-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171215_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='profile_images/default_profile_photo.jpg', upload_to='profile_images'),
        ),
    ]
