# Generated by Django 2.0.1 on 2018-01-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('cat_id', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('frequency', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('counter', models.PositiveIntegerField()),
            ],
        ),
    ]
