# Generated by Django 2.0 on 2018-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180102_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_habit_id', models.PositiveIntegerField()),
                ('datehash', models.CharField(default='1970-01-01', max_length=10)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('weekdays', models.CharField(default='', max_length=30)),
                ('numRepeats', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
    ]
