# Generated by Django 2.0 on 2018-01-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180116_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhabit',
            old_name='numRepeats',
            new_name='num_repeats',
        ),
    ]
