# Generated by Django 2.0 on 2018-01-17 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180117_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habithistory',
            name='user_habit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserHabit'),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
