# Generated by Django 2.0 on 2018-01-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180117_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habithistory',
            old_name='user_habit_id',
            new_name='user_habit',
        ),
        migrations.RenameField(
            model_name='userhabit',
            old_name='user_id',
            new_name='user',
        ),
    ]
